# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install required packages
RUN pip install pillow

# Copy the Python script into the container
COPY main.py /app/

# Define the entry point to run the Python script
ENTRYPOINT ["python", "main.py"]
